name: CI
on:
  push:

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cat /proc/sys/kernel/perf_event_paranoid
    - run: sudo sh -c 'echo 0 >/proc/sys/kernel/perf_event_paranoid'
    - run: cat /proc/sys/kernel/perf_event_paranoid
    - run: sudo perf stat ls || true
    - run: cargo build
    - run: sudo sh -c 'RUST_BACKTRACE=1 ./target/debug/perftest'
